name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test -- --coverage --maxWorkers 2
    - run: npx codecov
      # FIXME: codecov package is deprecated in favor of other solutions.
      # See:
      # - https://github.com/marketplace/actions/codecov
      # - https://about.codecov.io/blog/codecov-uploader-deprecation-plan/ 
      # - https://www.npmjs.com/package/codecov 
      if: false
      continue-on-error: true
